var GAME_LEVELS = [
  ["                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                              v                                                 ",
    "                                                                                ",
    "                                                                                ",
    "                                                            x     xxx           ",
    "                                                      xx      v  xx!xx          ",
    "                                       o o      xx               xx!xx          ",
    "                                                                 xx!xx          ",
    "                                       xxx                        xvx           ",
    "                                                                            xx  ",
    "  x                                        o o                               x  ",
    "  x  @                  o          x       xxx                               x  ",
    "  x                                x                                       o x  ",
    "  x          xxxxx      o          x                                o        x  ",
    "  x         xx   xx                x                             xxxxx       x  ",
    "  xxxxxxxxxxxx   xxxxxxxxxxxxxx    xxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
    "                              x    x                 x     x                    ",
    "                              x!!!!x                 x!!!!!x                    ",
    "                              x!!!!x                 x!!!!!x                    ",
    "                              xxxxxx                 xxxxxxx                    ",
    "                                                                                ",
    "                                                                                "],

  ["                                                               v                                               ",
    "                                                                                                               ",
    "                                                            x                                                  ",
    "                                                            x                                                  ",
    "                                                            x         xxx                                      ",
    "                                                            x                                                  ",
    "                                                            x                                                  ",
    "                                                            x    xx                                            ",
    "                                                            x  o  x                     o                      ",
    "                                                            x     x            x        x                      ",
    "                                                            xx    xx      o                 x                  ",
    "                              v                             x     x       x         x            o             ",
    "                            v                               x     x                              x             ",
    "                          v               o                 x    xx                                            ",
    "           oo           v                                   x  o  xx         o                                 ",
    "                                                o           x     x          x                x                ",
    "                                                            xx    x                     o             xxx xxx  ",
    "  @                                                               x                     x             x|x x|x  ",
    "                                     xx                          xxx    xx      o              xx     x     x  ",
    "         x!!!!x                      x=           xx              x     x       x               x     x     x  ",
    "        x!!!!!!x                     x      x      x              x     x!!!!!!!!!!!!!!!!!!!!!!!x     x     x  ",
    "       x!!!!!!!!x        o o o o     x!!!!!!!!!!!!!x              x     x!!!!!!!!!!!!!!!!!!!!!!!x     x  o  x  ",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  ],

  ["x                                                     x",
    "x                                                     x",
    "x                                                     x",
    "x                         o                           x",
    "x                                                    ox",
    "x                                                  xxxx",
    "x                                                 xxxxx",
    "x   o                                       =    xxxxxx",
    "x         xxxxxxx  x x x x x x x x xxx          xxxxxxx",
    "x      xxxx    |xx!x!x!x!x!x!x!x!x!xx          xxxxxxxx",
    "x                xxxxxxxxxxxxxxxxxxx          xxxxxxxxx",
    "x            o                                        x",
    "xx                                                  o x",
    "x                                           o         x",
    "x                                    o                x",
    "x                                                     x",
    "xx           x                                        x",
    "x                                                     x",
    "x                                             xx      x",
    "x                                        x     x      x",
    "x     xxxxx|    xxxxx     xxxxxxxxx            x      x",
    "x!!!!!xo  x!!!!!x  ox!!!!!x   o   x!!!!!!!!!!!!x      x",
    "xxxxxxx=  xxxxxxx=  xxxxxxx=     =xxxxxxxxxxxxxx     xx",
    "x                                                     x",
    "x  @                                                  x",
    "x                                                     x",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"




  ],










  ["                                                                                                  xxx x       ",
    "                                                                                                      x       ",
    "                                                                                                  xxxxx       ",
    "                                                                                                  x           ",
    "                                                                                                  x xxx       ",
    "                          o                                                                       x x x       ",
    "                                                                                             o o oxxx x       ",
    "                   xxx                                                                                x       ",
    "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
    "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
    "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
    "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
    "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
    "                                                                                                              ",
    "          o              xxx                              xx                                                  ",
    "                                                                                                              ",
    "                                                                                                              ",
    "                                                      xx                                                      ",
    "                   xxx         xxx                                                                            ",
    "                                                                                                              ",
    "                          o                                                     x      x                      ",
    "                                                          xx     xx                                           ",
    "             xxx         xxx         xxx                                 x                  x                 ",
    "                                                                                                              ",
    "                                                                 ||                                           ",
    "  xxxxxxxxxxx                                                                                                 ",
    "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
    "  x         x   x       x   x       x   x                 ||                  x     x                         ",
    "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
    "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
    "        x=                  =                =x   x                     xxx                                   ",
    "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
    "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
